fix crash when clicking invisible footer
the stack trace manifested as:
```
Version: Cheogram debug-local+free
Manufacturer: OnePlus
Device: OnePlus6
Timestamp: 2026-04-01 21:27:32 -0400
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:385)
	at java.util.ArrayList.get(ArrayList.java:434)
	at eu.siacs.conversations.ui.ManageAccountActivity.lambda$onCreate$3(ManageAccountActivity.java:140)
	at eu.siacs.conversations.ui.ManageAccountActivity.$r8$lambda$fcEx2bGWBsQPp04OkU82pOGEvUg(Unknown Source:0)
	at eu.siacs.conversations.ui.ManageAccountActivity$$ExternalSyntheticLambda0.onItemClick(D8$$SyntheticClass:0)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1274)
	at android.widget.AbsListView.onKeyUp(AbsListView.java:3511)
	at android.widget.ListView.commonKey(ListView.java:2498)
	at android.widget.ListView.onKeyUp(ListView.java:2371)
	at android.view.KeyEvent.dispatch(KeyEvent.java:3471)
	at android.view.View.dispatchKeyEvent(View.java:16521)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1982)
	at android.widget.ListView.dispatchKeyEvent(ListView.java:2346)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1987)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1987)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1987)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1987)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1987)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1987)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:462)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1971)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4557)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.kt:96)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.kt:110)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3397)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:376)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:8034)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7873)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7259)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7316)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7282)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7448)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7290)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7505)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7263)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7316)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7282)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7290)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7263)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7316)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7282)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7481)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:7721)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:5053)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:4430)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:4421)
	at android.view.inputmethod.InputMethodManager.-$$Nest$mfinishedInputEvent(Unknown Source:0)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:5030)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:181)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:387)
	at android.os.Looper.loopOnce(Looper.java:189)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8934)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```
notice that this required tab navigation, as the footer doesn't seem
visible, although maybe possible to hit it with your thumb idk. this is
especially tricky when the footer is invisible, i.e., when there aren't
any PSTN gateways configured